/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.v7.recyclerview;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f020028;
        public static final int coordinatorLayoutStyle = 0x7f020065;
        public static final int fastScrollEnabled = 0x7f02007a;
        public static final int fastScrollHorizontalThumbDrawable = 0x7f02007b;
        public static final int fastScrollHorizontalTrackDrawable = 0x7f02007c;
        public static final int fastScrollVerticalThumbDrawable = 0x7f02007d;
        public static final int fastScrollVerticalTrackDrawable = 0x7f02007e;
        public static final int font = 0x7f020080;
        public static final int fontProviderAuthority = 0x7f020082;
        public static final int fontProviderCerts = 0x7f020083;
        public static final int fontProviderFetchStrategy = 0x7f020084;
        public static final int fontProviderFetchTimeout = 0x7f020085;
        public static final int fontProviderPackage = 0x7f020086;
        public static final int fontProviderQuery = 0x7f020087;
        public static final int fontStyle = 0x7f020088;
        public static final int fontVariationSettings = 0x7f020089;
        public static final int fontWeight = 0x7f02008a;
        public static final int keylines = 0x7f02009a;
        public static final int layoutManager = 0x7f02009d;
        public static final int layout_anchor = 0x7f02009e;
        public static final int layout_anchorGravity = 0x7f02009f;
        public static final int layout_behavior = 0x7f0200a0;
        public static final int layout_dodgeInsetEdges = 0x7f0200ca;
        public static final int layout_insetEdge = 0x7f0200d3;
        public static final int layout_keyline = 0x7f0200d4;
        public static final int reverseLayout = 0x7f0200ff;
        public static final int spanCount = 0x7f02010b;
        public static final int stackFromEnd = 0x7f020111;
        public static final int statusBarBackground = 0x7f020113;
        